SELECT * FROM C##BTL.STUDENT_VIEW_GRADE_SCORE;
SELECT * FROM C##BTL.STUDENT_1_HEALTHRECORD;
SELECT * FROM C##BTL.STUDENT_1_VIEW_PARENT;
SELECT * FROM C##BTL.STUDENT_VIEW_COURSE;
SELECT * FROM C##BTL.STUDENT_1_VIEW_MATERIAL;
SELECT * FROM C##BTL.STUDENT_1_TIMETABLE;

