SELECT * FROM C##BTL.TEACHER_1_STUDENTS;
SELECT * FROM C##BTL.TEACHER_1_TIMETABLE;
SELECT * FROM C##BTL.TEACHER_1_INFO;
SELECT * FROM C##BTL.TEACHER_1_VIEW_UPDATE_EXAM;
BEGIN
    UPDATE C##BTL.TEACHER_1_VIEW_UPDATE_EXAM
    SET score = 90, grade = 'A'
    WHERE student_id = 1;
    COMMIT;
END;
BEGIN
    UPDATE C##BTL.TEACHER_1_VIEW_UPDATE_EXAM
    SET student_name = 'Not A'
    WHERE student_id = 1;
    COMMIT;
END;
SELECT * FROM C##BTL.TEACHER_VIEW_ALL_CLASSROOM;
SELECT * FROM C##BTL.TEACHER_1_VIEW_UPDATE_MATERIAL;
SELECT * FROM C##BTL.TEACHER_1_SPECIALIZATION;